artifact_location: /Users/lancesanterre/intern_2024/metaflow_scripts/your_mlflow_tracking_uri/0
creation_time: 1726765230551
experiment_id: '0'
last_update_time: 1726765230551
lifecycle_stage: active
name: Default
